class DataLists {
  static final List<String> listImages = [
    'assets/images/signup1.jpg',
    'assets/images/signup3.jpg',
    'assets/images/signup4.jpg',
    'assets/images/signup2.jpg',

    //'assets/images/signup1.jpg',
  ];
  static final List<String> creativity = [
    'Art',
    'Design',
    'Make-up',
    'Crafts',
    'Photography',
    'Writing',
    'Dancing',
    'Singing',
    'Puzzles',
    'BoardGames',
    'Reading'
  ];
  static final List<String> sports = [
    'Gym',
    'Football',
    'Cricket',
    'Hockey',
    'Athletics',
    'Badminton',
    'Squash',
    'Tennis',
    'BasketBall',
    'Running'
  ];
  static final List<String> smoking = ['Yes', 'No'];

  static final List<String> startSigns = [
    'Leo',
    'Pisces',
    'Aries',
    'Taurus',
    'Gemini',
    'Cancer',
    'Virgo',
    'Libra',
    'Scorpio',
    'Sagittarius',
    'Capricorn',
    'Aquarius'
  ];
  static final List<String> sect = [
    'Sunni',
    "Shi'a",
    'Ahmadi',
    'Prefer not to say'
  ];
  static final List<String> profileItems = [
    'Self',
    'Son',
    'Daughter',
    'Brother',
    'Sister',
    'Cousin',
    'Friend',
    'Relative'
  ];
  static final List<String> religionItems = [
    'Islam',
    'Judaism',
    'Hinduism',
    'Sikh',
    'Christianity',
    'Other'
  ];
  static final List<String> genderItems = ['Male', 'Female'];
  static final List<String> height = [
    "4'1",
    "4'2",
    "4'3",
    "4'4",
    "4'5",
    "4'6",
    "4'7",
    "4'8",
    "4'9",
    "4'10",
    "4'11",
    "5'0",
    "5'1",
    "5'2",
    "5'3",
    "5'4",
    "5'5",
    "5'6",
    "5'7",
    "5'8",
    "5'9",
    "5'10",
    "5'11",
    "6'0",
    "6'1",
    "6'2",
    "6'3",
    "6'4",
    "6'5",
    "6'6",
    "6'7",
    "6'8",
    "6'9",
    "6'10",
    "6'11"
  ];
  static final List<String> provinceList = [
    'Punjab',
    'Sindh',
    'Balochistan',
    'KPK',
    'Gilgit',
    'Azad Kashmir'
  ];
  static final List<String> maritalStatusList = [
    'Never Married',
    'Divorced',
    'Widowed',
    'Awaiting Divorced',
    'Annulled'
  ];
  static final List<String> childrenStatus = [
    'No',
    'Yes, Living together',
    'Yes, Not Living together ',
  ];
  static final List<String> listOfDays =
      List.generate(31, (index) => ('${index + 1}'));
  static final List<String> listOfYears =
      List.generate((73), (index) => '${2022 - index}');
  static final List<String> listOfMonth = [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec'
  ];

  static final List<String> communityItems = [
    'Punjabi',
    'Saraiki',
    'Urdu',
    'Bloachi',
    'Pushto',
    'Sindhi',
    'Kashmeri',
    'Other'
  ];

  static final List<String> cities = [
    "Lahore",
    "Karachi",
    "Faisalabad",
    "Rawalpindi",
    "Gujranwala",
    "Peshawar",
    "Multan",
    "Hyderabad",
    "Islamabad",
    "Quetta",
    "Bahawalpur",
    "Sargodha",
    "Sialkot",
    "Sukkur",
    "Larkana",
    "Rahim Yar Khan",
    "Sheikhupura",
    "Jhang",
    "Dera Ghazi Khan",
    "Gujrat",
    "Sahiwal",
    "Wah Cantonment",
    "Mardan",
    "Kasur",
    "Okara",
    "Mingora",
    "Nawabshah",
    "Chiniot",
    "Kotri",
    "Kāmoke",
    "Hafizabad",
    "Sadiqabad",
    "Mirpur Khas",
    "Burewala",
    "Kohat",
    "Khanewal",
    "Dera Ismail Khan",
    "Turbat",
    "Muzaffargarh",
    "Abbotabad",
    "Mandi Bahauddin",
    "Shikarpur",
    "Jacobabad",
    "Jhelum",
    "Khanpur",
    "Khairpur",
    "Khuzdar",
    "Pakpattan",
    "Hub",
    "Daska",
    "Gojra",
    "Dadu",
    "Muridke",
    "Bahawalnagar",
    "Samundri",
    "Tando Allahyar",
    "Tando Adam",
    "Jaranwala",
    "Chishtian",
    "Muzaffarabad",
    "Attock",
    "Vehari",
    "Kot Abdul Malik",
    "Ferozwala",
    "Chakwal",
    "Gujranwala Cantonment",
    "Kamalia",
    "Umerkot",
    "Ahmedpur East",
    "Kot Addu",
    "Wazirabad",
    "Mansehra",
    "Layyah",
    "Mirpur",
    "Swabi",
    "Chaman",
    "Taxila",
    "Nowshera",
    "Khushab",
    "Shahdadkot",
    "Mianwali",
    "Kabal",
    "Lodhran",
    "Hasilpur",
    "Charsadda",
    "Bhakkar",
    "Badin",
    "Arif Wala",
    "Ghotki",
    "Sambrial",
    "Jatoi",
    "Haroonabad",
    "Daharki",
    "Narowal",
    "Tando Muhammad Khan",
    "Kamber Ali Khan",
    "Mirpur Mathelo",
    "Kandhkot",
    "Bhalwal",
    "Gwadar",
  ];
  static final List<String> castItems = [
    "Arain",
    "Aulakh",
    "Ansari",
    "Awan",
    "Bahmani",
    "Bajwa",
    "Bangial",
    "Basra",
    "Baig",
    "Bhabra",
    "Batwal",
    "Bhati",
    "Barsar",
    "Buttar",
    "Chaudhry",
    "Chatha",
    "Chauhan",
    "Chughtai",
    "Derawal",
    "Dhariwal",
    "Dhillon",
    "Dogar",
    "Duggal",
    "Gakhar",
    "Gill",
    "Gujjar",
    "Gurmani",
    "Ibrahim",
    "Indra",
    "Iqbal",
    "Janjua",
    "Jatt",
    "Jutt",
    "Johiya",
    "Kathia",
    "Kahloon",
    "Khara",
    "Khan",
    "Khandowa",
    "Kharal",
    "Khokhar",
    "Kamboh",
    "Kirmani",
    "Sahni",
    "Khawaja",
    "Langra",
    "Langrial",
    "Lau",
    "Leel",
    "Longi",
    "Machi",
    "Mahar",
    "Mahtam",
    "Makhdoom",
    "Malik",
    "Meghwar",
    "Meo",
    "Mirza",
    "Mian",
    "Mighiana",
    "Minhas",
    "Mughal",
    "Muslim Khatris",
    "Rajput",
    "Nanda",
    "Naqvi",
    "Paracha",
    "Parihar",
    "Passi",
    "Patel",
    "Sheikh (Punjabi)",
    "Qureshi",
    "Raja",
    "Ranjha",
    "Roy",
    "Sahi clan",
    "Sangha",
    "Sanghera",
    "Satti",
    "Sehgal",
    "Sukhera",
    "Sethi",
    "Sirki",
    "Sangha",
    "Sheikh",
    "Shanzay",
    "Sial",
    "Siddiqui",
    "Singh",
    "Sidhu",
    "Sandhu",
    "Shah",
    "Tiwana",
    "Tarar",
    "Uzair",
    "Virk",
    "Warraich",
  ];
  static final List<String> qualificationList = [
    'School',
    'College',
    'University - Degree',
    'University - Masters',
    'University - Doctorate',
    'Prefer not to say'
  ];
  static final List<String> annualIncome = [
    '<50,000',
    '<60,000',
    '<70,000',
    '<80,000',
    '<90,000',
    '<100,000',
    '<5,00,000',
    '<10,00,000',
    '>10,00,000',
  ];

  static final List<String> occupationSector = [
    'Retail',
    'Sales',
    'Legal',
    'Healthcare',
    'Social care',
    'Recruitment and HR',
    'Media and internet',
    'Energy and utilities',
    'Business, consulting and management',
    'Information Technology',
    'Transport and logistics',
    'Property and construction',
    'Creative arts and design',
    'Charity and voluntary work',
    'Leisure, sport and tourism',
    'Science and pharmaceuticals',
    'Teacher training and education',
    'Marketing, advertising and PR',
    'Engineering and manufacturing',
    'Environment and agriculture',
    'Accountancy, banking and finance',
    'Hospitality and events management',
  ];
}
